use_frameworks!

target 'DataSources_Example' do
  pod 'Delegates', :git => 'https://github.com/johannesd/Delegates.git', :tag => '0.1.0'
  pod 'DataSources', :path => '../'

  target 'DataSources_Tests' do
    inherit! :search_paths

    
  end
end
